### ISSUE TITLE
crop view doesn't work on Windows

### ISSUE THREAD

**Issue by kkarwows** [asaglimbeni/clean-image-crop-uploader#3]
Crop view from clean-image-crop-uploader / cicu / views.py doesn't work on Windows. Problem is in line:

``` python
f = open(pathToFile, mode='r')
```

According to http://docs.python.org/2/tutorial/inputoutput.html#reading-and-writing-files it should be:

``` python
f = open(pathToFile, mode='rb')
```

It's safe both for Unix and Windows.

**Comment by asaglimbeni** [comment]
Hi Kkarwows,
yes it's right! It prefers to use 'rb' mode.
Thank you for your contribution!
Alfredo
